### PR TITLE
Enable gcc arch native, linktime and level O3 optimizations

### PR DESCRIPTION
**Pull request by Dark-Matter7232**

### CODE REVIEW

**Comment by siduck76** [comment]
what does this do?

**Comment by siduck76** [comment]
it increases compiling time instead :worried:

**Comment by Dark-Matter7232** [comment]
theoretically it should offer better performance

**Comment by siduck76** [comment]
> theoretically it should offer better performance

did you test it?

**Comment by Dark-Matter7232** [comment]
> > theoretically it should offer better performance
> 
> did you test it?

Either it will work or crash the whole process(that is if the code is not clean but in that case you can lower the optimization level to 02)

**Comment by siduck76** [comment]
would be great if you tested the performance and benchmarked them so I could know the difference.

**Pull request closed without merging**
