### PR TITLE
Patched hide and restore windows

### PR DESCRIPTION
**Pull request by Avimitin**
Implement #9 

Now you can use `<MOD>+e` and `<MOD>+<SHIFT>+e` to hide and restore windows.

### CODE REVIEW

**Comment by Avimitin** [comment]
That's how it looks like:

https://user-images.githubusercontent.com/30021675/128114158-07e59b67-d7da-4e87-9865-2b0760fdcfaa.mp4

**Comment by siduck76** [comment]
whoa! whats the compositor?

**Comment by siduck76** [comment]
I'll keep this on hold until this gets resolved . 

https://github.com/siduck76/chadwm/issues/6#issuecomment-891997192

**Comment by Avimitin** [comment]
> whoa! whats the compositor?

I am using [jonaburg/picom](https://github.com/jonaburg/picom)

And my picom configuration is [here](https://github.com/Avimitin/dotfile/blob/master/picom.conf)

**Review by siduck76 — APPROVED** [review]

**Pull request merged**
